version: '3'
services:
  customer-portal:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - customer-experience-db
  customer-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - customer-experience-db
  customer-experience-db:
    image: postgres
    environment:
      - POSTGRES_USER=customer-experience
      - POSTGRES_PASSWORD=customer-experience
      - POSTGRES_DB=customer-experience
