version: '3'
services:
  order-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - order-fulfillment-db
  order-fulfillment-db:
    image: postgres
    environment:
      - POSTGRES_USER=order-fulfillment
      - POSTGRES_PASSWORD=order-fulfillment
      - POSTGRES_DB=order-fulfillment
